name: Publish PyPI

on:
  push:
    tags:
      - "v*"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build_dist:
    uses: ./.github/workflows/_build_dist.yml
    with:
      rust_cache: false

  upload_pypi:
    needs: build_dist
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v4.3.0
        with:
          pattern: pypi-*
          path: dist
          merge-multiple: true
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
